#!/bin/bash

# Generate Loopback
echo "Generating v4l2-loopback device..."
sudo modprobe v4l2loopback devices=1 exclusive_caps=1

loopback=$(v4l2-ctl --list-devices | grep "Dummy video device" -A1 | grep "/dev")
elgato=$(v4l2-ctl --list-devices | grep "Cam Link" -A1 | grep "/dev")

if [[ $loopback == "" ]];then
	echo "No loopback device found!"
else
	echo "loopback=$loopback"
	echo "camlink=$elgato"
	echo -e "\e[34mUse 'Dummy Video Device' to use camera.\e[0m"
	echo -e "\e[31mCountdown beginning...\e[0m"
	for (( i = 5 ; i > 0 ; i--)); do
		sleep 1
		echo $i
	done
	sleep .5
	echo "Killing all programs using $elgato..."
	sleep .5
	fuser --kill /dev/video0
	echo "Starting FFmpeg..."
	sleep .5

	# Use ffmpeg to fix chroma and set up resolution
	ffmpeg -f v4l2 -input_format yuyv422 -framerate 60  -i $elgato -pix_fmt yuyv422 -codec copy -f v4l2 $loopback
fi
